### ISSUE TITLE
Server failed with error: 401 - Invalid Action

### ISSUE THREAD

**Issue by Mailaender** [lontivero/Open.NAT#20] opened 2015-03-20 14:05 UTC
Detection seems to work fine:

```
Open.NAT Information: 0 : Start Discovery
Thread started: <Thread Pool> #3
Thread started: <Thread Pool> #4
Open.NAT Information: 0 : Searching for: UpnpSearcher
Open.NAT Verbose: 0 : UPnP Response: HTTP/1.1 200 OK
LOCATION: http://192.168.178.1:49000/igddesc.xml
SERVER: FRITZ!Box 7490 UPnP/1.0 AVM FRITZ!Box 7490 113.06.24
CACHE-CONTROL: max-age=1800
EXT:
ST: urn:schemas-upnp-org:service:WANIPConnection:1
USN: uuid:75802409-bccb-40e7-8e6a-3481C4B451E8::urn:schemas-upnp-org:service:WANIPConnection:1

Open.NAT Information: 0 : UPnP Response: Router advertised a 'urn:schemas-upnp-org:service:WANIPConnection:1' service!!!
Open.NAT Information: 0 : Found device at: http://192.168.178.1:49000/igddesc.xml
Open.NAT Information: 0 : 192.168.178.1:49000: Fetching service list
Open.NAT Information: 0 : Found device at: http://192.168.178.1:49000/igddesc.xml

Open.NAT Information: 0 : 192.168.178.1:49000: Parsed services list
Open.NAT Information: 0 : 192.168.178.1:49000: Found service: urn:schemas-upnp-org:service:WANIPConnection:1
Open.NAT Information: 0 : 192.168.178.1:49000: Found upnp service at: /igdupnp/control/WANIPConn1
Open.NAT Information: 0 : 192.168.178.1:49000: Handshake Complete
Open.NAT Information: 0 : 192.168.178.1:49000: Absolute URI detected. Host address is now: 192.168.178.1:49000
Open.NAT Information: 0 : 192.168.178.1:49000: New control url: p/control/WANIPConn1
Open.NAT Information: 0 : Stop Discovery
```

But every actions fails with 401 for no reason like getting the external IP address:

```
Open.NAT Verbose: 0 : SOAPACTION: **GetExternalIPAddress** url:http://192.168.178.1:49000/p/control/WANIPConn1
Open.NAT Verbose: 0 : <s:Envelope 
   xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" 
   s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
   <s:Body>
      <u:GetExternalIPAddress xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1">
      </u:GetExternalIPAddress>
   </s:Body>
</s:Envelope>


Open.NAT Verbose: 0 : WebException status: ProtocolError
Open.NAT Warning: 0 : Server failed with error: 401 - Invalid Action
```

or mapping ports:

```
Open.NAT Verbose: 0 : SOAPACTION: **AddPortMapping** url:http://192.168.178.1:49000/p/control/WANIPConn1
Open.NAT Verbose: 0 : <s:Envelope 
   xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" 
   s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
   <s:Body>
      <u:AddPortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1">
         <NewRemoteHost></NewRemoteHost>
         <NewExternalPort>1234</NewExternalPort>
         <NewProtocol>TCP</NewProtocol>
         <NewInternalPort>1235</NewInternalPort>
         <NewInternalClient>192.168.178.29</NewInternalClient>
         <NewEnabled>1</NewEnabled>
         <NewPortMappingDescription>OpenRA</NewPortMappingDescription>
         <NewLeaseDuration>600</NewLeaseDuration>
      </u:AddPortMapping>
   </s:Body>
</s:Envelope>

Open.NAT Verbose: 0 : WebException status: ProtocolError
Open.NAT Warning: 0 : Server failed with error: 401 - Invalid Action
```

**Comment by lontivero** [comment] 2015-03-20 15:55
Ok, I will take a look at this today. Could you reboot your router and try again? This is just to be sure it is not a temporal router problem.

**Comment by Mailaender** [comment] 2015-03-20 16:16
Tried that. Did not help. It also works with Mono.Nat 1.2.21 so I am pretty sure it is a regression. Any pointers where I can start digging and patching?

**Comment by lontivero** [comment] 2015-03-20 19:55
If you could capture the full traffic using a proxy server like Fiddle2 that could help me a lot. The trace is not enough, sadly.

**Comment by lontivero** [comment] 2015-03-20 22:29
Well, I think that I found it. The problem seems to be here:
´´´
Open.NAT Information: 0 : 192.168.178.1:49000: Found upnp service at: /igdupnp/control/WANIPConn1
Open.NAT Information: 0 : 192.168.178.1:49000: Handshake Complete
Open.NAT Information: 0 : 192.168.178.1:49000: Absolute URI detected. Host address is now: 192.168.178.1:49000
Open.NAT Information: 0 : 192.168.178.1:49000: New control url: p/control/WANIPConn1
´´´

The new control url is wrong because it is *p/control/WANIPConn1* when it should be */igdupnp/control/WANIPConn1*. I couldn't reproduce it yet.

**Comment by lontivero** [comment] 2015-03-21 00:38
Could you try the change that I made in the [FritzRouter branch](https://github.com/lontivero/Open.NAT/tree/FritzRouter), please?

**Comment by Mailaender** [comment] 2015-03-21 07:37
I can confirm that your branch fixes it. The whole `Open.Nat.ConsoleTest` case runs fine now.

**Comment by Mailaender** [comment] 2015-03-21 07:38
Do you still need a full traffic capture?

**Comment by lontivero** [comment] 2015-03-21 17:17
No, the trace showed me the problem. I will close it after merge it to master. That will build and publish a new nuget package.

**Closed** 2015-03-25 19:25 UTC
